### ISSUE TITLE
repeats same video

### ISSUE THREAD

**Issue by Snootrat** [AutoMcG/steamdeck_tools#43]
it keeps playing the beter call saul boot video and idk how to fix it

**Comment by AutoMcG** [comment]
The way this works is probably very out of date with the newest version of SteamOS. I would recommend uninstalling it for now by running "random_service_uninstall.sh" in the vidswap directory or "uninstall_every_boot.desktop" from the root directory. 

If you need additional help, please feel free to reach out.
